# Generated by Django 4.1.6 on 2023-11-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('starting', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
