# Generated by Django 4.1.6 on 2023-11-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_watch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='id',
        ),
        migrations.AlterField(
            model_name='watch',
            name='list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auctions.listing'),
        ),
    ]
