# Generated by Django 4.1.6 on 2023-11-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_watch_id_alter_watch_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='list',
            new_name='list_watch',
        ),
    ]
